http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

# Enable monitoring for Logstash pipelines
xpack.monitoring.enabled: true

# Pipeline settings
pipeline.ordered: auto
pipeline.workers: 2